# version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: dynamic_hr_postgres
    restart: always
    environment:
      POSTGRES_DB: dynamic_hr_db
      POSTGRES_USER: dynamic_hr_user
      POSTGRES_PASSWORD: password
    ports:
      - "8002:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8003:8080"

volumes:
  pgdata:
